states_and_cities = {
    'abia': [
            "Aba",
            "Akwete",
            "Amaigbo",
            "Arochukwu",
            "Bende",
            "Ebem Ohafia",
            "Isiala Oboro",
            "Mbalano",
            "Nkwoagu Isuochi",
            "Ohafia-Ifigh",
            "Oke-Ikpe",
            "Okpuala-Ngwa",
            "Omoba",
            "Osisioma",
            "Umuahia"
        ],
    'adamawa': [
            "Demsa",
            "Fufore",
            "Ganye",
            "Gella",
            "Girei",
            "Gombi",
            "Gulak",
            "Guyuk",
            "Holma",
            "Hong",
            "Jada",
            "Jimeta",
            "Lamurde",
            "Madagali",
            "Maiha",
            "Mayo-Belwa",
            "Michika",
            "Mubi",
            "Ngurore",
            "Numan",
            "Shelleng",
            "Song",
            "Toungo",
            "Yola"
        ],
    'akwa ibom': [
        "Abak",
        "Abat",
        "Afaha Ikot Ebak",
        "Afaha Offiong",
        "Eket",
        "Enwang",
        "Esuk Oron",
        "Etinan",
        "Eyofin",
        "Ibiaku Ntok Okpo",
        "Idu",
        "Ikot Abasi",
        "Ikot Akpa Nkuk",
        "Ikot Edibon",
        "Ikot Ekpene",
        "Ikot Ibritam",
        "Itu",
        "Mkpat Enin",
        "Nto Edino",
        "Nung Udoe",
        "Odoro Ikpe",
        "Odot",
        "Oko Ita",
        "Okopedi",
        "Okoroete",
        "Oron",
        "Upenekang",
        "Uquo",
        "Urua Inyang",
        "Urue Offong",
        "Utu Etim Ekpo",
        "Uyo"
    ],
    'anambra': [
    "Abagana",
    "Achalla",
    "Aguata",
    "Agulu",
    "Ajalli",
    "Anaku",
    "Atani",
    "Awka",
    "Enugu-Ukwu",
    "Igbo-Ukwu",
    "Ihiala",
    "Neni",
    "Nkpor",
    "Nnewi",
    "Nteje",
    "Nzam",
    "Ogidi",
    "Ojoto",
    "Onitsha",
    "Otuocha",
    "Ozubulu",
    "Uga",
    "Ukpo",
    "Ukpor",
    "Umunze",
    "Uruobo-Okija"
]
,
    'bauchi': [
    "Alkaleri",
    "Azare",
    "Bauchi",
    "Bogoro",
    "Boi",
    "Bununu",
    "Dambam",
    "Darazo",
    "Dass",
    "Dindima",
    "Disina",
    "Gabarin",
    "Gamawa",
    "Giade",
    "Gwaram",
    "Itas",
    "Jama'are",
    "Kafin Madaki",
    "Kari",
    "Katagum",
    "Kirfi",
    "Lame",
    "Lere",
    "Madara",
    "Misau",
    "Ningi",
    "Sade",
    "Tafawa Balewa",
    "Toro",
    "Warji",
    "Yamrat",
    "Yana",
    "Yanda Bayo",
    "Yuli",
    "Zadawa",
    "Zalanga"
]
,
    'bayelsa': [
        "Amassoma",
        "Ekeremor",
        "Kaiama",
        "Nembe",
        "Ogbia",
        "Oporoma",
        "Sagbama",
        "Twon-Brass",
        "Yenagoa"
    ],
    'benue':  [
        "Adikpo",
        "Aliade",
        "Boju",
        "Buruku",
        "Gbajimba",
        "Gboko",
        "Igbor",
        "Igumale",
        "Katsina-Ala",
        "Lessel",
        "Makurdi",
        "Naka",
        "Obagaji",
        "Obarike-Ito",
        "Ochobo",
        "Oju",
        "Okpoga",
        "Otukpa",
        "Sankera",
        "Takum",
        "Tse-Agberagba",
        "Ugba",
        "Ugbokpo",
        "Vandeikya",
        "Wannune",
        "Yandev",
        "Zaki Biam"
]
,
    'borno': [
        "Askira",
        "Azare",
        "Bama",
        "Benisheikh",
        "Biu",
        "Bornu Yassu",
        "Briyel",
        "Chibok",
        "Damasak",
        "Damboa",
        "Dikwa",
        "Gajiram",
        "Gamboru",
        "Gubio",
        "Gudumbali",
        "Gwoza",
        "Khaddamari",
        "Konduga",
        "Kukawa",
        "Kwaya Kusar",
        "Mafa",
        "Magumeri",
        "Maiduguri",
        "Mallam Fatori",
        "Marte",
        "Miringa",
        "Monguno",
        "Ngala",
        "Rann",
        "Shaffa",
        "Shani",
        "Tokombere",
        "Uba",
        "Wuyo",
        "Yajiwa"
]
,
    'cross river': [
        "Abuochiche",
        "Akamkpa",
        "Akankpa",
        "Akpet Central",
        "Boje",
        "Calabar",
        "Effraya",
        "Gakem",
        "Ikang",
        "Ikom",
        "Ikot Nakanda",
        "Itigidi",
        "Obubra",
        "Obudu",
        "Odukpani",
        "Ogoja",
        "Okpoma",
        "Sankwala",
        "Ugep"
]
,
    'delta': [
    "Aboh",
    "Abraka",
    "Agbor",
    "Akwukwu-Igbo",
    "Asaba",
    "Bomadi",
    "Burutu",
    "Effurun",
    "Isiokolo",
    "Issele-Uku",
    "Koko",
    "Kwale",
    "Obiaruku",
    "Oghara",
    "Ogwashi-Uku",
    "Oleh",
    "Orerokpe",
    "Otor-Udu",
    "Otu-Jeremi",
    "Owa-Oyibu",
    "Ozoro",
    "Patani",
    "Sapele",
    "Ughelli",
    "Umunede",
    "Warri"
]
,
    'ebonyi': [
    "Abakaliki",
    "Afikpo",
    "Effium",
    "Ezillo",
    "Ezza-Ohu",
    "Ezzamgbo",
    "Iboko",
    "Isiaka",
    "Isieke",
    "Isu",
    "Nguzu Edda",
    "Obiozara",
    "Onuebonyi Echara",
    "Onueke",
    "Ugbodo"
]
,
    'edo': [
    "Abudu",
    "Afuze",
    "Agenebode",
    "Auchi",
    "Benin City",
    "Ehor",
    "Ekpoma",
    "Fugar",
    "Idogbo",
    "Igarra",
    "Igueben",
    "Iguobazuwa",
    "Illushi",
    "Irrua",
    "Okada",
    "Sabongida-Ora",
    "Siluko",
    "Ubiaja",
    "Uromi",
    "Uromi",
    "Uselu"
]
,
    'ekiti': [
    "Ado-Ekiti",
    "Aramoko-Ekiti",
    "Efon-Alaaye",
    "Emure-Ekiti",
    "Ido-Ekiti",
    "Ifaki",
    "Igbara-Odo",
    "Igede-Ekiti",
    "Ijero-Ekiti",
    "Ikere-Ekiti",
    "Ikole-Ekiti",
    "Ilawe-Ekiti",
    "Ipoti",
    "Ise-Ekiti",
    "Iye-Ekiti",
    "Ode-Ekiti",
    "Oke Ila",
    "Omuo-Ekiti",
    "Otun-Ekiti",
    "Oye-Ekiti"
]
,
    'enugu': [
    "Adani",
    "Agbani",
    "Aguobu-Owa",
    "Ake-Eze",
    "Aku",
    "Amagunze",
    "Awgu",
    "Eha Amufu",
    "Enugu",
    "Enugu-Ezike",
    "Ete",
    "Ibagwa-Aka",
    "Ikem",
    "Mberubu",
    "Ndeaboh",
    "Nkwo Nike",
    "Nsukka",
    "Obollo-Afor",
    "Obolo-Eke (1)",
    "Ogbede",
    "Oji River",
    "Opi",
    "Udi",
    "Umulona"
]
,
    'gombe': [
    "Akko",
    "Bajoga",
    "Bara",
    "Billiri",
    "Billiri",
    "Boh",
    "Dadiya",
    "Deba",
    "Dukku",
    "Garko",
    "Gombe",
    "Hinna",
    "Kafarati",
    "Kaltungo",
    "Kumo",
    "Mallam Sidi",
    "Nafada",
    "Pindiga",
    "Talasse"
]
,
    'imo': [
    "Aboh",
    "Afor-Oru",
    "Amaigbo",
    "Awo-Idemili",
    "Dikenafai",
    "Egbema",
    "Iho",
    "Isinweke",
    "Itu",
    "Mgbidi",
    "Nkwerre",
    "Nnenasa",
    "Nwaorieubi",
    "Oguta",
    "Okigwe",
    "Okwe",
    "Orlu",
    "Orodo",
    "Owerri",
    "Umuelemai",
    "Umuguma",
    "Umumma",
    "Umundugba",
    "Umuneke-Ngor",
    "Urualla"
]
,
    'jigawa': [
    "Auyo",
    "Babura",
    "Birnin Kudu",
    "Birniwa",
    "Dutse",
    "Gagarawa",
    "Gantsa",
    "Garki",
    "Gumel",
    "Guri",
    "Gwaram",
    "Gwiwa",
    "Hadejia",
    "Jahun",
    "Kafin Hausa",
    "Karkarna",
    "Kaugama",
    "Kazaure",
    "Kiri Kasamma",
    "Kiyawa",
    "Maigatari",
    "Malam Madori",
    "Mallammaduri",
    "Miga",
    "Ringim",
    "Roni",
    "Samamiya",
    "Sule Tankarkar",
    "Taura"
]
,
    'kaduna': [
    "Anchau",
    "Birnin Gwari",
    "Burumburum",
    "Dutsen Wai",
    "Giwa",
    "Gwantu",
    "Hunkuyi",
    "Igabi",
    "Ikara",
    "Kachia",
    "Kaduna",
    "Kafanchan",
    "Kagarko",
    "Kagoro",
    "Kajuru",
    "Kaura",
    "Kauru",
    "Kujama",
    "Kwoi",
    "Lere",
    "Maigana",
    "Makarfi",
    "Makera",
    "Mando",
    "Saminaka",
    "Soba",
    "Sofo-Birnin-Gwari",
    "Zaria",
    "Zonkwa"
]
,
    'kano': [
    "Ajingi",
    "Albasu",
    "Bagwai",
    "Bebeji",
    "Bichi",
    "Bunkure",
    "Dambatta",
    "Dan Gora",
    "Dawakin Kudu",
    "Dawakin Tofa",
    "Garko",
    "Garun Malam",
    "Gaya",
    "Gezawa",
    "Gwarzo",
    "Kabo",
    "Kano",
    "Karaye",
    "Kibiya",
    "Kiru",
    "Koguna",
    "Kumbotso",
    "Kunchi",
    "Kura",
    "Madobi",
    "Minjibir",
    "Rano",
    "Rimin Gado",
    "Ririwai",
    "Rogo",
    "Shanono",
    "Sumaila",
    "Takai",
    "Tofa",
    "Tsanyawa",
    "Tudun Wada",
    "Ungogo",
    "Warawa",
    "Wudil",
    "Zakirai"
]
,
    'katsina': [
    "Bakori",
    "Batagarawa",
    "Batsari",
    "Baure",
    "Bindawa",
    "Charanchi",
    "Dan Musa",
    "Dandume",
    "Danja",
    "Dankama",
    "Daura",
    "Dutsi",
    "Dutsin-Ma",
    "Faskari",
    "Funtua",
    "Gora",
    "Ingawa",
    "Jibia",
    "Jikamshi",
    "Kafur",
    "Kaita",
    "Kankara",
    "Kankia",
    "Katsina",
    "Kurfi",
    "Kusada",
    "Mai'Adua",
    "Malumfashi",
    "Mani",
    "Mashi",
    "Matazu",
    "Musawa",
    "Rimi",
    "Ruma",
    "Runka",
    "Sabuwa",
    "Safana",
    "Sandamu",
    "Wagini",
    "Zango"
]
,
    'kebbi': [
    "Aliero",
    "Argungu",
    "Augie",
    "Bagudo",
    "Bena",
    "Besse",
    "Bin Yauri",
    "Birnin Kebbi",
    "Bunza",
    "Bunza",
    "Dabai",
    "Dakingari",
    "Gulma",
    "Gwandu",
    "Jega",
    "Kalgo",
    "Kamba",
    "Kangiwa",
    "Kende",
    "Mahuta",
    "Maiyama",
    "Ribah",
    "Sakaba",
    "Shanga",
    "Wara",
    "Wasagu",
    "Yelwa",
    "Zuru"
]
,
    'kogi': [
    "Abejukolo",
    "Abocho",
    "Adogo",
    "Adoru",
    "Ajaka",
    "Ajaokuta",
    "Akpafa",
    "Ankpa",
    "Bugana",
    "Dekina",
    "Egbe",
    "Icheu",
    "Idah",
    "Isanlu",
    "Isanlu-Itedoijowa",
    "Iyara",
    "Kabba",
    "Koton-Karfe",
    "Lokoja",
    "Mopa",
    "Obangede",
    "Odo-Ere",
    "Ogaminana",
    "Oguma",
    "Ogurugu",
    "Okene",
    "Okpo",
    "Onyedega",
    "Ugwolawo"
]
,
    'kwara': [
    "Afon",
    "Ajasse Ipo",
    "Araromi-Opin",
    "Bode Saadu",
    "Fufu",
    "Gwasero",
    "Ilemona",
    "Iloffa",
    "Ilorin",
    "Jebba",
    "Kaiama",
    "Kosubosu",
    "Lafiagi",
    "Offa",
    "Oke-Oyi",
    "Okuta",
    "Omu-Aran",
    "Owu-Isin",
    "Patigi",
    "Share",
    "Suya",
    "Yashikera"
]
,
    'lagos': [
    "Agege",
    "Ajegunle",
    "Akodo",
    "Apapa",
    "Badagry",
    "Ebute Ikorodu",
    "Ebute-Metta",
    "Ejirin",
    "Epe",
    "Festac Town",
    "Ifako",
    "Ikeja",
    "Ikorodu",
    "Ikotun",
    "Ikoyi",
    "Lagos",
    "Makoko",
    "Mushin",
    "Ojota",
    "Oshodi",
    "Somolu",
    "Surulere"
]
,
    'nasarawa': [
    "Akwanga",
    "Awe",
    "Buga",
    "Doma",
    "Garaku",
    "Karu",
    "Keana",
    "Keffi",
    "Lafia",
    "Nasarawa",
    "Nasarawa Egon",
    "Obi",
    "Toto",
    "Wamba"
]
,
    'niger': [
    "Agaie",
    "Agwara",
    "Auna",
    "Babana",
    "Badeggi",
    "Bangi",
    "Baro",
    "Bida",
    "Bokani",
    "Duku",
    "Enagi",
    "Gawu Babangida",
    "Ibeto",
    "Kagara",
    "Katcha",
    "Konkwesso",
    "Kontagora",
    "Kusheriki",
    "Kuta",
    "Kutigi",
    "Lapai",
    "Lemu",
    "Maikunkele",
    "Mashegu",
    "Minna",
    "Mokwa",
    "Nasko",
    "New Bussa",
    "New Shagunnu",
    "Paiko",
    "Rijau",
    "Sabon Wuse",
    "Sarkin Pawa",
    "Suleja",
    "Tegina",
    "Ukata",
    "Wawa",
    "Wushishi",
    "Zungeru"
]
,
    'ogun': [
    "Abeokuta",
    "Abigi",
    "Ado Odo",
    "Atan",
    "Ayetoro",
    "Idi Iroko",
    "Ifo",
    "Ijebu-Ife",
    "Ijebu-Igbo",
    "Ijebu-Ode",
    "Ikenne",
    "Ilaro",
    "Imeko",
    "Iperu",
    "Ipokia",
    "Isara",
    "Itori",
    "Odeda",
    "Odogbolu",
    "Ogbere",
    "Ota",
    "Owode",
    "Shagamu"
]
,
    'ondo': [
    "Agbabu",
    "Akure",
    "Bolorunduro",
    "Idanre",
    "Ifon",
    "Igbara-Oke",
    "Igbekebo",
    "Igbokoda",
    "Iju",
    "Ikare",
    "Ilare",
    "Ile-Oluji",
    "Isua",
    "Ita-Ogbolu",
    "Ode",
    "Ode-Irele",
    "Oka",
    "Oke-Agbe",
    "Ondo",
    "Ore",
    "Owena",
    "Owo"
]
,
    'osun': [
    "Apomu",
    "Awo",
    "Bode Osi",
    "Ede",
    "Ejigbo",
    "Gbongan",
    "Ibokun",
    "Ifetedo",
    "Ifon",
    "Ijebu-Jesa",
    "Ikire",
    "Ikirun",
    "Ila Orangun",
    "Ile-Ife",
    "Ile-Ogbo",
    "Ilesa",
    "Ilobu",
    "Inisa",
    "Iperindo",
    "Ipetumodu",
    "Iragbiji",
    "Iwo",
    "Modakeke",
    "Oke Mesi",
    "Okuku",
    "Olupona",
    "Osogbo",
    "Osu",
    "Otan Ayegbaju",
    "Oyan"
]
,
    'oyo': [
    "Ago Are",
    "Ago-Amodu",
    "Ajaawa",
    "Akanran",
    "Alapa",
    "Ayete",
    "Egbeda",
    "Eruwa",
    "Fiditi",
    "Ibadan",
    "Idi-Ayunre",
    "Ido",
    "Igbeti",
    "Igbo-Ora",
    "Igboho",
    "Ikoyi-Ile",
    "Iresa-Adu",
    "Iseyin",
    "Iwere-Ile",
    "Iyana-Ofa",
    "Jobele",
    "Kisi",
    "Lalupon",
    "Moniya",
    "Ogbomoso",
    "Okeho",
    "Orita Eruwa",
    "Otu",
    "Oyo",
    "Saki",
    "Tede"
]
,
    'plateau': [
    "Amper",
    "Angware",
    "Baap",
    "Barkin Ladi",
    "Bassa",
    "Bokkos",
    "Bukuru",
    "Dengi",
    "Jos",
    "Kwal",
    "Kwolla",
    "Langtang",
    "Mabudi",
    "Mangu",
    "Pankshin",
    "Panyam",
    "Riyom",
    "Shendam",
    "Tunkus",
    "Vom",
    "Wase",
    "Yelwa"
]
,
    'rivers': [
    "Abonnema",
    "Abua",
    "Afam",
    "Ahoada",
    "Akinima",
    "Bonny",
    "Bori",
    "Buguma",
    "Degema",
    "Degema Hulk",
    "Eberi",
    "Elele",
    "Emuoha",
    "Isiokpo",
    "Kpor",
    "Nchia",
    "Ngo",
    "Obonoma",
    "Ogu",
    "Okehi",
    "Okrika",
    "Omoku",
    "Opobo",
    "Port Harcourt",
    "Rumuodomaya",
    "Saakpenwa"
]
,
    'sokoto': [
    "Balle",
    "Binji",
    "Bodinga",
    "Dange",
    "Gada",
    "Gandi",
    "Gidan Madi",
    "Goronyo",
    "Gwadabawa",
    "Illela",
    "Isa",
    "Kebbe",
    "Kware",
    "Rabah",
    "Sabon Birni",
    "Shagari",
    "Silame",
    "Sokoto",
    "Tambuwal",
    "Tureta",
    "Wamako",
    "Wurno",
    "Yabo"
]
,
    'taraba': [
    "Baissa",
    "Beli",
    "Donga",
    "Gassol",
    "Gembu",
    "Ibi",
    "Jalingo",
    "Karim Lamido",
    "Lau",
    "Lissam",
    "Mutum Biyu",
    "Pantisawa",
    "Riti",
    "Serti",
    "Sunkani",
    "Wukari",
    "Zing"
]
,
    'yobe': [
    "Babban Gida",
    "Bara",
    "Buni Yadi",
    "Damagum",
    "Damaturu",
    "Dankalwa",
    "Dapchi",
    "Daura",
    "Fika",
    "Gashua",
    "Geidam",
    "Goniri",
    "Gorgoram",
    "Gujba",
    "Gwio Kura",
    "Jajimaji",
    "Jakusko",
    "Kanamma",
    "Kumagunnam",
    "Lajere",
    "Machina",
    "Nguru",
    "Potiskum",
    "Sabon Garin Nangere"
]
,
    'zamfara': [
    "Anka",
    "Bakura",
    "Birnin Magaji",
    "Bukkuyum",
    "Bungudu",
    "Dan Sadau",
    "Gummi",
    "Gusau",
    "Kaura Namoda",
    "Kwatarkwashi",
    "Maradun",
    "Maru",
    "Moriki",
    "Sauri",
    "Shinkafi",
    "Talata Mafara",
    "Tsafe",
    "Zurmi"
]

}
